let userName = "Tomáš";
console.log(userName)

userName = "Honzík";
console.log(useName)

console.log(7+4);
console.log("7"+"4");
console.log("A"+"B");
console.log("7"+4);

let age = 31;
console.log(age > 20);

let text = "Text"
console.log(typeof text)

let a;
console.log(a);
let b = null;
console.log(b)

let isLoggedIn = false;
console.log(typeof isLoggedIn)

// Aritmetická operace

let cisloA = 10;
let cisloB = 5;
console.log(cisloA + cisloB);
console.log(cisloA - cisloB);
console.log(cisloA * cisloB);
console.log(cisloA / cisloB);

// omocňování **

console.log(cisloA ** cisloB);

// zbytek - modulo

console.log(cisloA % cisloB);

console.log(cisloA + cisloB * cisloB);

console.log((cisloA + cisloB) * cisloB);

// Aktualiízace proměnné (přiřazovací operátory)

let number = 10;
number = number + 1;
number += 1;
number -= 2;
number *= 6;
number /= 6;
number %= 3;
number ++;
number --;

console.log(number);